import type { Condition, Field, Option, RepeatGroup, Section } from "./types";
import { SETTLEMENTS, MOBILISER_CODES } from "./settlements";

/**
 * Janman Purnea Household Baseline Tool — full questionnaire (Sections A–O).
 *
 * `label.en` holds an English rendering of each question. `label.hi` is left
 * empty on purpose: the authoritative Hindi field-facing text must be filled
 * from the master questionnaire (it did not survive PDF extraction). The UI
 * shows `hi` when present and falls back to `en`.
 */

export const FORM_VERSION = "V0.1";

const o = (code: string, en: string): Option => ({ code, en });
const consentYes: Condition = { field: "consent_given", eq: "yes" };
/** Section is only reached once consent is given. */
const gated = (trigger?: Condition): Condition =>
  trigger ? { all: [consentYes, trigger] } : consentYes;

/* ─── Section A: Survey details ─────────────────────────────── */
const sectionA: Section = {
  id: "A",
  title: { en: "Survey details" },
  items: [
    {
      qid: "A1",
      name: "form_version",
      label: { en: "Form version" },
      type: "select",
      options: [o("V0.1", "V0.1"), o("V1.0", "V1.0")],
      required: true,
      defaultValue: FORM_VERSION,
      note: "Update after the final version is approved and frozen.",
    },
    {
      qid: "A2",
      name: "survey_date",
      label: { en: "Survey date" },
      type: "date",
      required: true,
      note: "Prefer an automatically captured date.",
    },
    {
      qid: "A3",
      name: "mobiliser_name",
      label: { en: "Mobiliser name" },
      type: "select",
      options: [],
      required: true,
      note: "Auto-filled from the logged-in mobiliser account.",
    },
    {
      qid: "A4",
      name: "mobiliser_code",
      label: { en: "Mobiliser code" },
      type: "select",
      options: MOBILISER_CODES.map((c) => o(c, c)),
      required: true,
      note: "Used in the household ID; auto-filled from the account.",
    },
    {
      qid: "A5",
      name: "settlement_name",
      label: { en: "Settlement / area" },
      type: "select",
      options: SETTLEMENTS.map((s) => o(s.code, s.label)),
      required: true,
    },
    {
      qid: "A7",
      name: "gps_location",
      label: { en: "Location / GPS" },
      type: "geopoint",
      required: false,
      note: "Collected only for project mapping; optional during pilot.",
    },
    {
      qid: "A8",
      name: "household_landmark",
      label: { en: "Household landmark" },
      type: "text",
      required: false,
      note: "A simple landmark is sufficient; do not record a full address.",
    },
    {
      qid: "A9",
      name: "respondent_name",
      label: { en: "Respondent name" },
      type: "text",
      required: true,
      note: "The respondent should be an adult household member.",
    },
    {
      qid: "A10",
      name: "respondent_relation",
      label: { en: "Respondent's relation to household head" },
      type: "select",
      options: [
        o("head", "Head"),
        o("spouse", "Spouse"),
        o("parent", "Parent"),
        o("son_daughter", "Son / Daughter"),
        o("other_relative", "Other relative"),
        o("other", "Other"),
      ],
      required: true,
    },
    {
      qid: "A11",
      name: "respondent_phone",
      label: { en: "Respondent phone" },
      type: "phone",
      required: false,
      validation: { digits: 10 },
      note: "May be used for project follow-up.",
    },
  ],
};

/* ─── Section B: Consent ────────────────────────────────────── */
const sectionB: Section = {
  id: "B",
  title: { en: "Consent" },
  items: [
    {
      qid: "B1",
      name: "consent_text",
      label: { en: "Consent script (read aloud to the respondent)" },
      type: "note",
      required: true,
      note: "Read the consent script before continuing.",
    },
    {
      qid: "B2",
      name: "consent_given",
      label: { en: "Did the respondent give consent to continue?" },
      type: "select",
      options: [o("yes", "Yes"), o("no", "No")],
      required: true,
      note: "If No, end the form.",
    },
  ],
};

/* ─── Section C: Basic household details ────────────────────── */
const sectionC: Section = {
  id: "C",
  title: { en: "Basic household details" },
  showWhen: gated(),
  items: [
    {
      qid: "C1",
      name: "head_name",
      label: { en: "Household head's name" },
      type: "text",
      required: true,
    },
    {
      qid: "C2",
      name: "hh_total_members",
      label: { en: "How many members live in this household?" },
      type: "integer",
      required: true,
      validation: { min: 1, max: 25 },
      note: "Count only members who ordinarily live here.",
    },
    {
      qid: "C3",
      name: "hh_type",
      label: { en: "Household type" },
      type: "select",
      options: [
        o("nuclear", "Nuclear family"),
        o("joint", "Joint family"),
        o("single", "Single-person household"),
        o("other", "Other"),
      ],
      required: true,
    },
    {
      qid: "C4",
      name: "years_in_settlement",
      label: { en: "How long has the household lived in this settlement?" },
      type: "select",
      options: [
        o("less_1", "Less than 1 year"),
        o("1_3", "1–3 years"),
        o("4_10", "4–10 years"),
        o("more_10", "More than 10 years"),
        o("since_birth", "Since birth / always"),
        o("dont_know", "Don't know"),
      ],
      required: true,
    },
    {
      qid: "C5",
      name: "migration_status",
      label: { en: "Do members go outside for work?" },
      type: "select",
      options: [
        o("no", "No"),
        o("seasonal", "Seasonally"),
        o("one_or_more", "One or more members go outside"),
        o("whole_family_moves", "Whole family moves"),
      ],
      required: true,
    },
    {
      qid: "C6",
      name: "main_livelihood",
      label: { en: "Main source of household livelihood" },
      type: "select",
      options: [
        o("daily_wage", "Daily wage labour"),
        o("informal_work", "Informal / odd work"),
        o("rickshaw_driver", "Rickshaw / auto / e-rickshaw"),
        o("domestic_work", "Domestic work"),
        o("small_business", "Small business / shop"),
        o("salaried", "Salaried"),
        o("rag_picking", "Rag / scrap picking"),
        o("no_regular_income", "No regular income"),
        o("other", "Other"),
      ],
      required: true,
    },
    {
      qid: "C7",
      name: "monthly_income_range",
      label: { en: "Approximate monthly household income" },
      type: "select",
      options: [
        o("less_5000", "Below ₹5,000"),
        o("5000_10000", "₹5,000–₹10,000"),
        o("10001_15000", "₹10,001–₹15,000"),
        o("15001_25000", "₹15,001–₹25,000"),
        o("more_25000", "Above ₹25,000"),
        o("irregular", "Irregular"),
        o("refused", "Refused to answer"),
      ],
      required: false,
    },
    {
      qid: "C8",
      name: "housing_type",
      label: { en: "Type of house" },
      type: "select",
      options: [
        o("kaccha", "Kaccha"),
        o("semi_pucca", "Semi-pucca"),
        o("pucca", "Pucca"),
        o("temporary", "Temporary / shelter"),
        o("rented", "Rented"),
        o("other", "Other"),
      ],
      required: true,
    },
    {
      qid: "C9",
      name: "social_group",
      label: { en: "Social group (only if comfortable sharing)" },
      type: "select",
      options: [
        o("sc", "SC"),
        o("st", "ST"),
        o("obc", "OBC"),
        o("minority", "Minority"),
        o("general", "General"),
        o("other", "Other"),
        o("no_response", "No response"),
      ],
      required: false,
      note: "Never pressure the respondent to answer.",
    },
  ],
};

/* ─── Section D: Household member roster (repeat) ───────────── */
const rosterMember: RepeatGroup = {
  kind: "repeat",
  qid: "D0",
  name: "household_members",
  label: { en: "Household members" },
  countFrom: "hh_total_members",
  showWhen: consentYes,
  fields: [
    { qid: "D1", name: "member_name", label: { en: "Member name" }, type: "text", required: true },
    {
      qid: "D2",
      name: "member_age",
      label: { en: "Age" },
      type: "integer",
      required: true,
      validation: { min: 0, max: 110 },
    },
    {
      qid: "D3",
      name: "member_gender",
      label: { en: "Gender" },
      type: "select",
      options: [o("female", "Female"), o("male", "Male"), o("other", "Other"), o("no_response", "No response")],
      required: true,
    },
    {
      qid: "D4",
      name: "member_relation",
      label: { en: "Relation to head" },
      type: "select",
      options: [
        o("head", "Head"),
        o("spouse", "Spouse"),
        o("son", "Son"),
        o("daughter", "Daughter"),
        o("parent", "Parent"),
        o("sibling", "Sibling"),
        o("grandchild", "Grandchild"),
        o("daughter_in_law", "Daughter-in-law"),
        o("son_in_law", "Son-in-law"),
        o("other_relative", "Other relative"),
        o("non_relative", "Non-relative"),
      ],
      required: true,
    },
    {
      qid: "D5",
      name: "member_marital_status",
      label: { en: "Marital status" },
      type: "select",
      options: [
        o("unmarried", "Unmarried"),
        o("married", "Married"),
        o("widow", "Widow / widower"),
        o("separated", "Separated"),
        o("divorced", "Divorced"),
        o("not_applicable", "Not applicable"),
      ],
      requiredWhen: { field: "member_age", gte: 15 },
    },
    {
      qid: "D6",
      name: "member_education_status",
      label: { en: "Education status" },
      type: "select",
      options: [
        o("not_school_age", "Not of school age yet"),
        o("never_enrolled", "Never enrolled"),
        o("currently_school", "Currently in school"),
        o("currently_college", "Currently in college"),
        o("dropped_out", "Dropped out"),
        o("completed", "Completed"),
        o("adult_no_school", "Adult, never went to school"),
        o("dont_know", "Don't know"),
      ],
      required: true,
    },
    {
      qid: "D7",
      name: "member_work_status",
      label: { en: "Work / activity status" },
      type: "select",
      options: [
        o("child", "Child"),
        o("student", "Student"),
        o("paid_work", "Paid work"),
        o("unpaid_work", "Unpaid / household work"),
        o("seeking_work", "Seeking work"),
        o("unable_work", "Unable to work"),
        o("elderly", "Elderly"),
        o("other", "Other"),
      ],
      required: true,
    },
    {
      qid: "D8",
      name: "member_disability",
      label: { en: "Any disability?" },
      type: "select",
      options: [
        o("no", "No"),
        o("yes_cert", "Yes — with certificate"),
        o("yes_no_cert", "Yes — without certificate"),
        o("dont_know", "Don't know"),
        o("no_response", "No response"),
      ],
      required: true,
      note: "Ask sensitively; do not make any diagnosis.",
    },
    {
      qid: "D9",
      name: "member_phone",
      label: { en: "Phone (optional, for follow-up)" },
      type: "phone",
      required: false,
      validation: { digits: 10 },
    },
  ],
};

const sectionD: Section = {
  id: "D",
  title: { en: "Household member roster" },
  showWhen: gated(),
  items: [rosterMember],
};

/* ─── Section E: Target group counts ────────────────────────── */
const intCount = (qid: string, name: string, en: string, note?: string): Field => ({
  qid,
  name,
  label: { en },
  type: "integer",
  required: true,
  validation: { min: 0 },
  note,
});

const sectionE: Section = {
  id: "E",
  title: { en: "Target group counts" },
  showWhen: gated(),
  items: [
    intCount("E1", "num_children_0_3", "Number of children aged 0–3"),
    intCount("E2", "num_children_4_12", "Number of children aged 4–12"),
    intCount("E3", "num_youth_13_24", "Number of youth aged 13–24"),
    intCount("E4", "num_women_15_49", "Number of women aged 15–49"),
    {
      qid: "E5",
      name: "has_pregnant_or_lactating",
      label: { en: "Any pregnant woman or new mother (delivered in last 6 months)?" },
      type: "select",
      options: [o("yes", "Yes"), o("no", "No"), o("dont_know", "Don't know"), o("no_response", "No response")],
      required: true,
    },
    intCount("E6", "num_elderly_60plus", "Number of elderly (60+)", "Used for pension follow-up."),
    {
      qid: "E7",
      name: "has_widow_single_woman",
      label: { en: "Any widow / single woman needing support?" },
      type: "select",
      options: [o("yes", "Yes"), o("no", "No"), o("no_response", "No response")],
      required: false,
    },
    {
      qid: "E8",
      name: "has_pwd_member",
      label: { en: "Any person with disability in the household?" },
      type: "select",
      options: [o("yes", "Yes"), o("no", "No"), o("no_response", "No response")],
      required: true,
    },
  ],
};

/* ─── Section F: Documents and entitlements ─────────────────── */
const sectionF: Section = {
  id: "F",
  title: { en: "Documents and entitlements" },
  showWhen: gated(),
  items: [
    {
      qid: "F1",
      name: "all_have_aadhaar",
      label: { en: "Do all household members have Aadhaar?" },
      type: "select",
      options: [
        o("all", "All"),
        o("some", "Some"),
        o("none", "None"),
        o("correction", "Some need correction / update"),
        o("dont_know", "Don't know"),
      ],
      required: true,
    },
    {
      qid: "F2",
      name: "has_ration_card",
      label: { en: "Does the household have a ration / PDS card?" },
      type: "select",
      options: [
        o("yes", "Yes"),
        o("no", "No"),
        o("applied", "Applied"),
        o("not_received", "Applied / not received"),
        o("dont_know", "Don't know"),
      ],
      required: true,
    },
    {
      qid: "F3",
      name: "ration_card_issue",
      label: { en: "What issue is there with the ration card?" },
      type: "multiselect",
      options: [
        o("no_card", "No card"),
        o("names_missing", "Names missing"),
        o("wrong_details", "Wrong details"),
        o("not_getting_ration", "Not getting ration"),
        o("migrated_issue", "Migration-related issue"),
        o("other", "Other"),
      ],
      showWhen: { field: "has_ration_card", ne: "yes" },
      required: false,
    },
    {
      qid: "F4",
      name: "has_ayushman_card",
      label: { en: "Does the household have an Ayushman card?" },
      type: "select",
      options: [
        o("all", "All eligible members have it"),
        o("some", "Some"),
        o("none", "None"),
        o("dont_know", "Don't know"),
      ],
      required: true,
    },
    {
      qid: "F5",
      name: "has_bank_account",
      label: { en: "Does anyone have an active bank account?" },
      type: "select",
      options: [o("yes", "Yes"), o("no", "No"), o("dont_know", "Don't know")],
      required: true,
    },
    {
      qid: "F6",
      name: "birth_cert_children",
      label: { en: "Do children have birth certificates?" },
      type: "select",
      options: [
        o("all", "All have it"),
        o("some", "Some"),
        o("none", "None"),
        o("no_children", "No children"),
        o("dont_know", "Don't know"),
      ],
      showWhen: {
        expr: (v) =>
          Number(v.num_children_0_3 || 0) + Number(v.num_children_4_12 || 0) > 0,
      },
    },
    {
      qid: "F7",
      name: "pension_need",
      label: { en: "Is any pension needed in the household?" },
      type: "multiselect",
      options: [
        o("old_age", "Old-age pension"),
        o("widow", "Widow pension"),
        o("disability", "Disability pension"),
        o("none", "None"),
        o("dont_know", "Don't know"),
      ],
      required: true,
    },
    {
      qid: "F8",
      name: "maternity_benefit_status",
      label: { en: "Maternity benefit (PMMVY / JSY) status" },
      type: "select",
      options: [
        o("yes", "Yes"),
        o("no", "No"),
        o("already_getting", "Already getting it"),
        o("dont_know", "Don't know"),
      ],
      showWhen: { field: "has_pregnant_or_lactating", eq: "yes" },
    },
    {
      qid: "F9",
      name: "other_docs_needed",
      label: { en: "Any other documents / certificates needed?" },
      type: "multiselect",
      options: [
        o("voter_id", "Voter ID"),
        o("caste_cert", "Caste certificate"),
        o("income_cert", "Income certificate"),
        o("residence_cert", "Residence certificate"),
        o("disability_cert", "Disability certificate"),
        o("school_docs", "School documents"),
        o("other", "Other"),
        o("none", "None"),
      ],
      required: false,
    },
    {
      qid: "F10",
      name: "entitlement_followup_required",
      label: { en: "Is entitlement follow-up required?" },
      type: "select",
      options: [o("yes", "Yes"), o("no", "No"), o("maybe", "Maybe")],
      required: true,
    },
  ],
};

/* ─── Section G: Health access ──────────────────────────────── */
const sectionG: Section = {
  id: "G",
  title: { en: "Health access" },
  showWhen: gated(),
  items: [
    {
      qid: "G1",
      name: "usual_health_place",
      label: { en: "Where does the household usually go when unwell?" },
      type: "select",
      options: [
        o("govt_hospital", "Government hospital"),
        o("govt_phc", "Government PHC / clinic"),
        o("private_clinic", "Private clinic / hospital"),
        o("local_provider", "Local / informal provider"),
        o("pharmacy", "Pharmacy"),
        o("no_fixed", "No fixed place"),
        o("other", "Other"),
      ],
      required: true,
    },
    {
      qid: "G2",
      name: "uses_govt_health",
      label: { en: "How often does the household use govt. health facilities?" },
      type: "select",
      options: [
        o("often", "Often"),
        o("sometimes", "Sometimes"),
        o("rarely", "Rarely"),
        o("never", "Never"),
        o("dont_know", "Don't know"),
      ],
      required: true,
    },
    {
      qid: "G3",
      name: "health_barriers",
      label: { en: "Main problems in reaching health facilities" },
      type: "multiselect",
      options: [
        o("distance", "Distance"),
        o("cost", "Cost"),
        o("documents", "Documents"),
        o("behaviour", "Staff behaviour"),
        o("long_wait", "Long wait"),
        o("dont_know_where", "Don't know where to go"),
        o("no_problem", "No problem"),
        o("other", "Other"),
      ],
      required: true,
    },
    {
      qid: "G4",
      name: "knows_asha_anm_aww",
      label: { en: "Does the household know the ASHA / ANM / Anganwadi worker?" },
      type: "select",
      options: [
        o("all", "Knows all / most"),
        o("some", "Knows some"),
        o("none", "Knows none"),
        o("dont_know", "Don't know"),
      ],
      required: true,
    },
    {
      qid: "G5",
      name: "chronic_or_serious_illness",
      label: { en: "Anyone with a chronic or serious illness needing support?" },
      type: "select",
      options: [o("yes", "Yes"), o("no", "No"), o("no_response", "No response")],
      required: false,
      note: "Do not ask for a diagnosis; capture only the reported need.",
    },
    {
      qid: "G6",
      name: "health_referral_need",
      label: { en: "Any health referral need for the household?" },
      type: "select",
      options: [
        o("urgent", "Urgent"),
        o("routine", "Routine follow-up"),
        o("no", "No"),
        o("dont_know", "Don't know"),
      ],
      required: true,
    },
    {
      qid: "G7",
      name: "health_referral_details",
      label: { en: "What kind of health follow-up is needed?" },
      type: "multiselect",
      options: [
        o("pregnant_woman", "Pregnant woman"),
        o("child_health", "Child health / immunisation"),
        o("chronic_illness", "Chronic illness"),
        o("disability", "Disability"),
        o("emergency", "Urgent emergency"),
        o("nutrition", "Nutrition"),
        o("other", "Other"),
      ],
      showWhen: { field: "health_referral_need", in: ["urgent", "routine"] },
    },
  ],
};

/* ─── Section H: Maternal health ────────────────────────────── */
const hasPreg: Condition = { field: "has_pregnant_or_lactating", eq: "yes" };
const sectionH: Section = {
  id: "H",
  title: { en: "Maternal health, pregnancy and ICDS" },
  showWhen: gated(hasPreg),
  items: [
    {
      qid: "H1",
      name: "preg_lactating_name",
      label: { en: "Name of pregnant woman / new mother" },
      type: "text",
      required: true,
      note: "If more than one, record additional names in the note.",
    },
    {
      qid: "H2",
      name: "pregnancy_month",
      label: { en: "If pregnant, which month?" },
      type: "select",
      options: [
        o("m1_3", "1–3 months"),
        o("m4_6", "4–6 months"),
        o("m7_9", "7–9 months"),
        o("delivered_recently", "Delivered recently"),
        o("dont_know", "Don't know"),
        o("no_response", "No response"),
      ],
    },
    {
      qid: "H3",
      name: "registered_with_asha_anm",
      label: { en: "Registered with ASHA / ANM for pregnancy / new mother care?" },
      type: "select",
      options: [o("yes", "Yes"), o("no", "No"), o("dont_know", "Don't know")],
    },
    {
      qid: "H4",
      name: "anc_checkup_done",
      label: { en: "Any ANC / check-up done?" },
      type: "select",
      options: [
        o("yes", "Yes"),
        o("no", "No"),
        o("dont_know", "Don't know"),
        o("not_applicable", "Not applicable"),
      ],
      showWhen: { field: "pregnancy_month", ne: "delivered_recently" },
    },
    {
      qid: "H5",
      name: "number_anc",
      label: { en: "How many pregnancy check-ups so far?" },
      type: "integer",
      validation: { min: 0 },
      showWhen: { field: "anc_checkup_done", eq: "yes" },
    },
    {
      qid: "H6",
      name: "icds_linked",
      label: { en: "Getting Anganwadi / ICDS / THR services?" },
      type: "select",
      options: [
        o("yes", "Yes"),
        o("no", "No"),
        o("irregular", "Irregular"),
        o("dont_know", "Don't know"),
      ],
    },
    {
      qid: "H7",
      name: "delivery_plan_place",
      label: { en: "Where is delivery planned?" },
      type: "select",
      options: [
        o("govt_hospital", "Government hospital"),
        o("private", "Private hospital / clinic"),
        o("home", "Home"),
        o("not_decided", "Not decided"),
        o("no_response", "No response"),
      ],
      showWhen: { field: "pregnancy_month", in: ["m4_6", "m7_9"] },
    },
    {
      qid: "H8",
      name: "pregnancy_warning_reported",
      label: { en: "Any warning sign reported to ASHA / ANM?" },
      type: "select",
      options: [
        o("yes", "Yes"),
        o("no", "No"),
        o("dont_know", "Don't know"),
        o("no_response", "No response"),
      ],
    },
    {
      qid: "H9",
      name: "maternal_followup_required",
      label: { en: "Maternal health follow-up needed?" },
      type: "select",
      options: [o("urgent", "Urgent"), o("routine", "Routine follow-up"), o("no", "No")],
      required: true,
    },
  ],
};

/* ─── Section I: Children aged 0–3 (repeat) ─────────────────── */
const child03: RepeatGroup = {
  kind: "repeat",
  qid: "I0",
  name: "children_0_3",
  label: { en: "Children aged 0–3" },
  countFrom: "num_children_0_3",
  showWhen: gated({ field: "num_children_0_3", gt: 0 }),
  fields: [
    { qid: "I1", name: "child_0_3_name", label: { en: "Child's name" }, type: "text", required: true },
    {
      qid: "I2",
      name: "child_0_3_age_months",
      label: { en: "Age in completed months" },
      type: "integer",
      required: true,
      validation: { min: 0, max: 47 },
    },
    {
      qid: "I3",
      name: "child_0_3_gender",
      label: { en: "Gender" },
      type: "select",
      options: [o("female", "Female"), o("male", "Male"), o("other", "Other"), o("no_response", "No response")],
      required: true,
    },
    {
      qid: "I4",
      name: "child_0_3_birth_certificate",
      label: { en: "Does the child have a birth certificate?" },
      type: "select",
      options: [o("yes", "Yes"), o("no", "No"), o("applied", "Applied"), o("dont_know", "Don't know")],
      required: true,
    },
    {
      qid: "I5",
      name: "child_0_3_anganwadi_linked",
      label: { en: "Linked with Anganwadi?" },
      type: "select",
      options: [
        o("regular", "Yes, regularly"),
        o("irregular", "Sometimes / irregular"),
        o("no", "No"),
        o("dont_know", "Don't know"),
      ],
      required: true,
    },
    {
      qid: "I6",
      name: "child_0_3_immunisation_status",
      label: { en: "Immunisation status" },
      type: "select",
      options: [
        o("up_to_date", "Up to date"),
        o("partial", "Partial"),
        o("none", "None"),
        o("dont_know", "Don't know / no card"),
      ],
      required: true,
    },
    {
      qid: "I7",
      name: "child_0_3_growth_monitoring",
      label: { en: "Weighed / growth monitored recently?" },
      type: "select",
      options: [o("yes", "Yes"), o("no", "No"), o("dont_know", "Don't know")],
      required: true,
    },
    {
      qid: "I8",
      name: "child_0_3_support_need",
      label: { en: "What support does the child need?" },
      type: "multiselect",
      options: [
        o("health_check", "Health check"),
        o("immunisation", "Immunisation"),
        o("anganwadi_linkage", "Anganwadi linkage"),
        o("nutrition", "Nutrition"),
        o("birth_certificate", "Birth certificate"),
        o("none", "No support needed"),
        o("other", "Other"),
      ],
      required: true,
      note: "Do not select 'No support needed' together with another option.",
    },
    {
      qid: "I9",
      name: "child_0_3_followup_required",
      label: { en: "Is follow-up required for this child?" },
      type: "select",
      options: [o("yes", "Yes"), o("no", "No"), o("maybe", "Maybe")],
      required: true,
    },
  ],
};

const sectionI: Section = {
  id: "I",
  title: { en: "Children aged 0–3" },
  showWhen: gated({ field: "num_children_0_3", gt: 0 }),
  items: [child03],
};

/* ─── Section J: Children 4–12 and education (repeat) ───────── */
const child412: RepeatGroup = {
  kind: "repeat",
  qid: "J0",
  name: "children_4_12",
  label: { en: "Children aged 4–12" },
  countFrom: "num_children_4_12",
  showWhen: gated({ field: "num_children_4_12", gt: 0 }),
  fields: [
    { qid: "J1", name: "child_name", label: { en: "Child's name" }, type: "text", required: true },
    {
      qid: "J2",
      name: "child_age",
      label: { en: "Age" },
      type: "integer",
      required: true,
      validation: { min: 4, max: 12 },
    },
    {
      qid: "J3",
      name: "child_gender",
      label: { en: "Gender" },
      type: "select",
      options: [o("girl", "Girl"), o("boy", "Boy"), o("other", "Other"), o("no_response", "No response")],
      required: true,
    },
    {
      qid: "J4",
      name: "child_school_status",
      label: { en: "School status" },
      type: "select",
      options: [
        o("school_regular", "In school — regular"),
        o("school_irregular", "In school — irregular"),
        o("enrolled_not_attending", "Enrolled but not attending"),
        o("never_enrolled", "Never enrolled"),
        o("dropped_out", "Dropped out"),
        o("awc_only", "Anganwadi only"),
        o("dont_know", "Don't know"),
      ],
      required: true,
    },
    {
      qid: "J5",
      name: "school_name",
      label: { en: "School / Anganwadi name" },
      type: "text",
      showWhen: {
        field: "child_school_status",
        in: ["school_regular", "school_irregular", "enrolled_not_attending", "awc_only"],
      },
    },
    {
      qid: "J6",
      name: "child_class",
      label: { en: "Class" },
      type: "select",
      options: [
        o("awc", "Anganwadi"),
        o("class1", "Class 1"),
        o("class2", "Class 2"),
        o("class3", "Class 3"),
        o("class4", "Class 4"),
        o("class5", "Class 5"),
        o("class6plus", "Class 6 or above"),
        o("dont_know", "Don't know"),
      ],
      showWhen: {
        field: "child_school_status",
        in: ["school_regular", "school_irregular", "enrolled_not_attending"],
      },
    },
    {
      qid: "J7",
      name: "reason_not_in_school",
      label: { en: "Why is the child not in school regularly?" },
      type: "multiselect",
      options: [
        o("documents", "Documents"),
        o("cost", "Cost / fees / expenses"),
        o("distance", "Distance"),
        o("work_care", "Work / caregiving at home"),
        o("migration", "Migration"),
        o("disability_health", "Disability / health"),
        o("not_interested", "Not interested"),
        o("parents_not_ready", "Parents not ready"),
        o("school_refused", "School refused admission"),
        o("other", "Other"),
      ],
      showWhen: { field: "child_school_status", ne: "school_regular" },
    },
    {
      qid: "J8",
      name: "parent_willing_school",
      label: { en: "Are parents willing to send the child to school regularly?" },
      type: "select",
      options: [
        o("yes", "Yes"),
        o("no", "No"),
        o("maybe", "Maybe"),
        o("already_regular", "Already regular"),
      ],
      required: true,
    },
    {
      qid: "J9",
      name: "child_education_followup",
      label: { en: "School / enrolment follow-up needed for this child?" },
      type: "select",
      options: [o("yes", "Yes"), o("no", "No"), o("maybe", "Maybe")],
      required: true,
    },
  ],
};

const sectionJ: Section = {
  id: "J",
  title: { en: "Children 4–12 and education" },
  showWhen: gated({ field: "num_children_4_12", gt: 0 }),
  items: [child412],
};

/* ─── Section K: Youth 13–24 (repeat) ───────────────────────── */
const youth: RepeatGroup = {
  kind: "repeat",
  qid: "K0",
  name: "youth_13_24",
  label: { en: "Youth aged 13–24" },
  countFrom: "num_youth_13_24",
  showWhen: gated({ field: "num_youth_13_24", gt: 0 }),
  fields: [
    { qid: "K1", name: "youth_name", label: { en: "Youth name" }, type: "text", required: true },
    {
      qid: "K2",
      name: "youth_age",
      label: { en: "Age" },
      type: "integer",
      required: true,
      validation: { min: 13, max: 24 },
    },
    {
      qid: "K3",
      name: "youth_gender",
      label: { en: "Gender" },
      type: "select",
      options: [o("female", "Female"), o("male", "Male"), o("other", "Other"), o("no_response", "No response")],
      required: true,
    },
    {
      qid: "K4",
      name: "youth_status",
      label: { en: "Current status" },
      type: "select",
      options: [
        o("school", "School"),
        o("college", "College"),
        o("work", "Working"),
        o("home", "At home"),
        o("seeking_work", "Seeking work"),
        o("dropped_out", "Dropped out"),
        o("other", "Other"),
      ],
      required: true,
    },
    {
      qid: "K5",
      name: "youth_group_interest",
      label: { en: "Interested in a youth group / meeting?" },
      type: "select",
      options: [
        o("yes", "Yes"),
        o("maybe", "Maybe"),
        o("no", "No"),
        o("not_asked", "Not asked"),
      ],
      required: true,
    },
    {
      qid: "K6",
      name: "youth_interest_topics",
      label: { en: "Which topics is the youth interested in?" },
      type: "multiselect",
      options: [
        o("health", "Health"),
        o("nutrition", "Nutrition"),
        o("education", "Education"),
        o("career", "Career / jobs"),
        o("gender", "Gender"),
        o("rights", "Rights"),
        o("sports", "Sports"),
        o("life_skills", "Life skills"),
        o("marriage", "Marriage / age of marriage"),
        o("community_action", "Community action"),
        o("other", "Other"),
      ],
      showWhen: { field: "youth_group_interest", in: ["yes", "maybe"] },
    },
    {
      qid: "K7",
      name: "youth_preferred_time",
      label: { en: "Preferred meeting time" },
      type: "select",
      options: [
        o("morning", "Morning"),
        o("afternoon", "Afternoon"),
        o("evening", "Evening"),
        o("sunday", "Sunday / holiday"),
        o("depends", "Depends"),
      ],
      showWhen: { field: "youth_group_interest", in: ["yes", "maybe"] },
    },
    {
      qid: "K8",
      name: "potential_youth_leader",
      label: { en: "Potential group leader / active volunteer?" },
      type: "select",
      options: [o("yes", "Yes"), o("maybe", "Maybe"), o("no", "No"), o("dont_know", "Don't know")],
      required: true,
    },
    {
      qid: "K9",
      name: "youth_followup_required",
      label: { en: "Youth group follow-up needed?" },
      type: "select",
      options: [o("yes", "Yes"), o("no", "No"), o("maybe", "Maybe")],
      required: true,
    },
  ],
};

const sectionK: Section = {
  id: "K",
  title: { en: "Youth 13–24" },
  showWhen: gated({ field: "num_youth_13_24", gt: 0 }),
  items: [youth],
};

/* ─── Section L: Women and adolescent girls ─────────────────── */
const womenInterest: Condition = {
  field: "women_session_interest",
  in: ["yes", "maybe"],
};
const sectionL: Section = {
  id: "L",
  title: { en: "Women and adolescent girls" },
  showWhen: gated(),
  items: [
    {
      qid: "L1",
      name: "women_session_interest",
      label: { en: "Interest in women / adolescent-girl sessions (health, rights, etc.)?" },
      type: "select",
      options: [
        o("yes", "Yes"),
        o("maybe", "Maybe"),
        o("no", "No"),
        o("not_applicable", "Not applicable"),
      ],
      required: true,
    },
    {
      qid: "L2",
      name: "women_preferred_time",
      label: { en: "Preferred meeting time" },
      type: "select",
      options: [
        o("morning", "Morning"),
        o("afternoon", "Afternoon"),
        o("evening", "Evening"),
        o("depends", "Depends"),
      ],
      showWhen: womenInterest,
    },
    {
      qid: "L3",
      name: "women_topics_needed",
      label: { en: "Which topics are needed?" },
      type: "multiselect",
      options: [
        o("health", "Health"),
        o("nutrition", "Nutrition"),
        o("periods", "Periods / menstruation"),
        o("pregnancy", "Pregnancy"),
        o("icds", "Anganwadi / ICDS"),
        o("schemes", "Government schemes"),
        o("gender", "Gender"),
        o("violence_safety", "Violence / safety"),
        o("education", "Education"),
        o("other", "Other"),
      ],
      showWhen: womenInterest,
      note: "Ask gently — this is a sensitive topic.",
    },
    {
      qid: "L4",
      name: "safe_meeting_space",
      label: { en: "Safe / preferred meeting space" },
      type: "select",
      options: [
        o("community_space", "Community space"),
        o("awc", "Anganwadi"),
        o("school", "School"),
        o("someone_home", "Someone's home"),
        o("open_space", "Open space"),
        o("not_sure", "Not sure"),
      ],
      required: false,
    },
  ],
};

/* ─── Section M: Community issues and basic amenities ───────── */
const sectionM: Section = {
  id: "M",
  title: { en: "Community issues and basic amenities" },
  showWhen: gated(),
  items: [
    {
      qid: "M1",
      name: "water_issue",
      label: { en: "Is there a problem getting clean drinking water?" },
      type: "select",
      options: [
        o("no_issue", "No issue"),
        o("irregular", "Irregular supply"),
        o("far", "Source is far"),
        o("unsafe", "Water is unsafe"),
        o("no_source", "No source / buy water"),
        o("other", "Other"),
      ],
      required: true,
    },
    {
      qid: "M2",
      name: "toilet_access",
      label: { en: "Toilet access" },
      type: "select",
      options: [
        o("own", "Own"),
        o("shared", "Shared / community"),
        o("open", "Open defecation"),
        o("paid", "Paid toilet"),
        o("other", "Other"),
      ],
      required: true,
    },
    {
      qid: "M3",
      name: "drainage_issue",
      label: { en: "Drainage / water-logging problem?" },
      type: "select",
      options: [
        o("severe", "Severe"),
        o("sometimes", "Sometimes"),
        o("no", "No"),
        o("dont_know", "Don't know"),
      ],
      required: true,
    },
    {
      qid: "M4",
      name: "electricity_access",
      label: { en: "Electricity access" },
      type: "select",
      options: [
        o("regular", "Regular"),
        o("irregular", "Irregular"),
        o("no", "No"),
        o("shared", "Shared / temporary"),
        o("other", "Other"),
      ],
      required: false,
    },
    {
      qid: "M5",
      name: "waste_issue",
      label: { en: "Garbage / waste problem?" },
      type: "select",
      options: [
        o("severe", "Severe"),
        o("moderate", "Moderate"),
        o("no", "No problem"),
        o("dont_know", "Don't know"),
      ],
      required: false,
    },
    {
      qid: "M6",
      name: "safety_concern",
      label: { en: "Any safety concern in the settlement?" },
      type: "select",
      options: [o("yes", "Yes"), o("no", "No"), o("no_response", "No response")],
      required: false,
      note: "Record details only if the respondent is comfortable.",
    },
    {
      qid: "M7",
      name: "top_community_issues",
      label: { en: "Top 3 problems in the settlement" },
      type: "multiselect",
      options: [
        o("water", "Water"),
        o("toilet", "Toilet"),
        o("drainage", "Drainage"),
        o("road", "Road"),
        o("waste", "Waste"),
        o("electricity", "Electricity"),
        o("health", "Health"),
        o("school", "School"),
        o("documents", "Documents"),
        o("safety", "Safety"),
        o("livelihood", "Livelihood"),
        o("other", "Other"),
      ],
      required: true,
      validation: { maxSelect: 3 },
    },
  ],
};

/* ─── Section N: Follow-up and priority tagging ─────────────── */
const followupYesMaybe: Condition = {
  field: "followup_required",
  in: ["yes", "maybe"],
};
const sectionN: Section = {
  id: "N",
  title: { en: "Follow-up and priority tagging" },
  showWhen: gated(),
  items: [
    {
      qid: "N1",
      name: "followup_required",
      label: { en: "Does this household need project follow-up?" },
      type: "select",
      options: [o("yes", "Yes"), o("no", "No"), o("maybe", "Maybe")],
      required: true,
      note: "Key question for household action planning.",
    },
    {
      qid: "N2",
      name: "followup_type",
      label: { en: "What kind of follow-up?" },
      type: "multiselect",
      options: [
        o("entitlement", "Entitlement / document"),
        o("health", "Health referral"),
        o("maternal", "Maternal / pregnancy / ANC"),
        o("icds", "Anganwadi / ICDS"),
        o("child_school", "Child school / enrolment"),
        o("youth", "Youth group"),
        o("women_session", "Women / girls' session"),
        o("pension", "Pension"),
        o("disability", "Disability support"),
        o("urgent", "Urgent vulnerability"),
        o("other", "Other"),
      ],
      showWhen: followupYesMaybe,
      required: true,
    },
    {
      qid: "N3",
      name: "priority_level",
      label: { en: "Follow-up priority level" },
      type: "select",
      options: [
        o("high", "High — urgent follow-up"),
        o("medium", "Medium"),
        o("low", "Low"),
      ],
      showWhen: followupYesMaybe,
      required: true,
      note: "Use High only for genuinely urgent cases.",
    },
    {
      qid: "N4",
      name: "next_action",
      label: { en: "Next action(s)" },
      type: "multiselect",
      options: [
        o("revisit", "Revisit the household"),
        o("collect_docs", "Check / collect documents"),
        o("asha_anm", "Connect with ASHA / ANM"),
        o("awc", "Send to Anganwadi"),
        o("school", "Send to school"),
        o("add_youth", "Add to youth group list"),
        o("add_child", "Add to child enrolment list"),
        o("entitlement_tracker", "Add to entitlement tracker"),
        o("discuss_pm", "Discuss with PM"),
        o("escalate", "Escalate to Director / PM"),
        o("no_action", "No action needed"),
      ],
      required: true,
    },
    {
      qid: "N5",
      name: "next_followup_date",
      label: { en: "Next follow-up date" },
      type: "date",
      showWhen: followupYesMaybe,
    },
    {
      qid: "N6",
      name: "mobiliser_observation",
      label: { en: "Mobiliser's observation" },
      type: "textarea",
      required: false,
      note: "Record only essential observations.",
    },
    {
      qid: "N7",
      name: "case_story_potential",
      label: { en: "Relevant for a future case story / learning?" },
      type: "select",
      options: [o("yes", "Yes"), o("no", "No"), o("maybe", "Maybe")],
      required: false,
      note: "Obtain separate consent later before developing any case story.",
    },
  ],
};

/* ─── Section O: Closing ────────────────────────────────────── */
const sectionO: Section = {
  id: "O",
  title: { en: "Closing" },
  showWhen: gated(),
  items: [
    {
      qid: "O1",
      name: "closing_note",
      label: { en: "Closing script (read aloud)" },
      type: "note",
      required: true,
    },
    {
      qid: "O2",
      name: "respondent_questions",
      label: { en: "Any questions or expectations from the household?" },
      type: "textarea",
      required: false,
    },
    {
      qid: "O3",
      name: "interview_start_time",
      label: { en: "Interview start time" },
      type: "time",
      required: false,
    },
    {
      qid: "O4",
      name: "interview_end_time",
      label: { en: "Interview end time" },
      type: "time",
      required: false,
    },
    {
      qid: "O5",
      name: "form_complete_status",
      label: { en: "Form completion status" },
      type: "select",
      options: [
        o("complete", "Complete"),
        o("partial", "Partial"),
        o("refused_midway", "Refused midway"),
      ],
      required: true,
    },
    {
      qid: "O6",
      name: "reason_incomplete",
      label: { en: "Reason form is incomplete" },
      type: "select",
      options: [
        o("respondent_busy", "Respondent busy"),
        o("refused", "Refused"),
        o("technical", "Technical issue"),
        o("sensitive", "Sensitive topic"),
        o("other", "Other"),
      ],
      showWhen: { field: "form_complete_status", ne: "complete" },
    },
  ],
};

export const QUESTIONNAIRE: Section[] = [
  sectionA,
  sectionB,
  sectionC,
  sectionD,
  sectionE,
  sectionF,
  sectionG,
  sectionH,
  sectionI,
  sectionJ,
  sectionK,
  sectionL,
  sectionM,
  sectionN,
  sectionO,
];
